name: Vera Icona
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0.4215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2a292e'
    - '#dad9d5'
    - '#47566b'
    - '#7f859f'
  brandStrength: 0.28534663445316255
  lightness: 0.060592999681830406
  saturation: 0.2890802910551429
  rhythmicContrast: 0.33478070236742496
purpose: []
